# Nom du workflow
name: My Workflow
# Condition pour lancer le workflow
on: [push]
# Tâches à effectuer
jobs:
  mon-premier-job:
    runs-on: ubuntu-latest
    steps:
      - run : echo "mon premier job a été lancé"
    #Deuxième tâche
  mon-deeuxieme-job:
    runs-on: ubuntu-latest
    steps:
      - run : echo "mon deuxième job"
      - run : echo "mon test de job"
